---
title: "Mod 4 Challenges"
author: "Reese Hotten-Somers"
date: "2023-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

##Challenge 1:
v <- c("Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.")
str_split(v, NULL)[[2]]

I attempted to extract every third element but I.  found some trouble along the way
x <- "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed."
n <- 40
f<- 32
strsplit(gsub(paste0("([[:alnum:]]{",    
                     n,
                     "})"),
              "\\1 ",
              x),
        split = "f")[[1]]

##Challenge 2:
m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
m
x<-m[,c(2,3,6)]
x
x<-m[c(6,8),]
x

##Challenge 3:
a<- array(data = 400:1, dim= c(5,5,4,4))
a //creates array with numbers decending from 400-1 with they dimensions of 5,5,4,4
a[1,1,1,2]
a[2,3,2,]
a[1:5,1:5,3,3]


##Challenge 4:
Platyrrhini<- c("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini<- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Tarsioidea <-c("Tarsiidae")
Anthropoidea <- list(Catarrhini, Platyrrhini)
names(Antrhopoidea)<- list("Catarrhini", "Platyrrhini")
Haplorhini<- list(Anthropoidea, Tarsioidea)
names(Haplorhini)<- list("Anthropoidea", "Tarsioidea")
Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae",
    "Daubentoniidae")
Lorisoidea <- c("Lorisidae", "Galagidae")
Strepsirhini <- list(Lemuroidea, Lorisoidea)
names(Strepsirhini) <- list("Lemuroidea", "Lorisoidea")
Primates<- list(Haplorhini, Strepsirhini)
names(Primates)<- list("Haplorhini", "Strepsirhini")
Primates
//creating lists

##Challenge 5:
d1<- c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2) //data for matrix
m3<- matrix(d1, nrow=5, ncol=3, byrow=TRUE) //creates matrix with 5 rows/3 colums using d1 as data
m3
df<- data.frame(m3) //converts matrix into data frame do it can be manipulated differently
df
as.logical(df$X2) //makes column 2 logical valued
df
as.factor(df$X3) // makes colum 3 factor valued
str(df)

